import type { GalleryItem } from "@/components/gallery/gallery-grid"

// Datos de ejemplo para cada categoría
export const galleryData: Record<string, GalleryItem[]> = {
  fashion: [
    {
      id: 1,
      title: "Colección Primavera 2024",
      description: "Sesión fotográfica para la nueva colección de moda primavera-verano.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "fashion",
    },
    {
      id: 2,
      title: "Campaña Publicitaria",
      description: "Campaña para marca de ropa exclusiva.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "fashion",
    },
    {
      id: 3,
      title: "Behind the Scenes",
      description: "Detrás de cámaras de nuestra última sesión de moda.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "fashion",
    },
    {
      id: 4,
      title: "Desfile Milano 2023",
      description: "Cobertura del desfile de moda en Milano.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "fashion",
    },
    {
      id: 5,
      title: "Lookbook Otoño",
      description: "Lookbook para colección de otoño.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "fashion",
    },
    {
      id: 6,
      title: "Entrevista Diseñador",
      description: "Entrevista exclusiva con diseñador reconocido.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "fashion",
    },
  ],
  urban: [
    {
      id: 1,
      title: "Proyecto Urbano Centro",
      description: "Fotografía urbana en el centro de la ciudad.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "urban",
    },
    {
      id: 2,
      title: "Arquitectura Moderna",
      description: "Estudio de arquitectura moderna en entornos urbanos.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "urban",
    },
    {
      id: 3,
      title: "Timelapse Ciudad",
      description: "Timelapse de la ciudad durante 24 horas.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "Urban",
    },
    {
      id: 4,
      title: "Street Art",
      description: "Documentación de arte urbano y grafiti.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "urban",
    },
    {
      id: 5,
      title: "Vida Nocturna",
      description: "La ciudad que nunca duerme.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "Urban",
    },
    {
      id: 6,
      title: "Documental Urbano",
      description: "Documental sobre la transformación urbana.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "urban",
    },
  ],
  events: [
    {
      id: 1,
      title: "Festival de Música",
      description: "Cobertura del festival de música anual.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "events",
    },
    {
      id: 2,
      title: "Conferencia Tech",
      description: "Evento tecnológico internacional.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "events",
    },
    {
      id: 3,
      title: "Highlights Evento Corporativo",
      description: "Resumen del evento corporativo anual.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "events",
    },
    {
      id: 4,
      title: "Gala Benéfica",
      description: "Fotografías de la gala benéfica anual.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "events",
    },
    {
      id: 5,
      title: "Lanzamiento de Producto",
      description: "Evento exclusivo de lanzamiento.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "events",
    },
    {
      id: 6,
      title: "Aftermovie Festival",
      description: "Aftermovie oficial del festival.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "events",
    },
  ],
  food: [
    {
      id: 1,
      title: "Gastronomía Gourmet",
      description: "Fotografía de platos gourmet para restaurante de alta cocina.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "food",
    },
    {
      id: 2,
      title: "Campaña Restaurante",
      description: "Campaña publicitaria para cadena de restaurantes.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "food",
    },
    {
      id: 3,
      title: "Proceso de Preparación",
      description: "Video del proceso de preparación de platos exclusivos.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "food",
    },
    {
      id: 4,
      title: "Menú Degustación",
      description: "Fotografía para menú de degustación.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "food",
    },
    {
      id: 5,
      title: "Bebidas Artesanales",
      description: "Sesión de cócteles y bebidas artesanales.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "Food",
    },
    {
      id: 6,
      title: "Entrevista Chef",
      description: "Entrevista con chef reconocido.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "food",
    },
  ],
  industry: [
    {
      id: 1,
      title: "Procesos Industriales",
      description: "Documentación de procesos industriales avanzados.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "industry",
    },
    {
      id: 2,
      title: "Instalaciones Modernas",
      description: "Fotografía de instalaciones industriales modernas.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "industry",
    },
    {
      id: 3,
      title: "Tour Virtual Fábrica",
      description: "Tour virtual por las instalaciones de producción.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "industry",
    },
    {
      id: 4,
      title: "Maquinaria Especializada",
      description: "Fotografía de maquinaria industrial especializada.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "industry",
    },
    {
      id: 5,
      title: "Seguridad Industrial",
      description: "Campaña de seguridad industrial.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "industry",
    },
    {
      id: 6,
      title: "Proceso de Producción",
      description: "Video del proceso de producción completo.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "industry",
    },
  ],
  corporate: [
    {
      id: 1,
      title: "Retratos Corporativos",
      description: "Sesión de retratos para equipo directivo.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "corporate",
    },
    {
      id: 2,
      title: "Oficinas Modernas",
      description: "Fotografía de espacios de trabajo modernos.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "corporate",
    },
    {
      id: 3,
      title: "Video Corporativo",
      description: "Video corporativo para presentación de empresa.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "corporate",
    },
    {
      id: 4,
      title: "Reunión Ejecutiva",
      description: "Fotografía de reunión ejecutiva.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "corporate",
    },
    {
      id: 5,
      title: "Cultura Empresarial",
      description: "Documentación de la cultura empresarial.",
      type: "image",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "/placeholder.svg?height=1200&width=800",
      category: "corporate",
    },
    {
      id: 6,
      title: "Testimonios Empleados",
      description: "Video de testimonios de empleados.",
      type: "video",
      thumbnail: "/placeholder.svg?height=400&width=400",
      src: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      category: "corporate",
    },
  ],
}

